import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Header from "@/components/header/header";
import navLogo from '@/assets/grouplogo.png';


const inter = Inter({ subsets: ["latin"] });

// metadata : <head></head> 태그에 들어갈 코드 
export const metadata = {
  title: "우리 동아리",
  description: "Generated by create next app",
  icons:{
    icon:'/grouplogo.png'    
  } 
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <Header/>
        {/* children == page.js */}
        {children}
        </body>
    </html>
  );
}

// 기본생성시
// layous.js  : page.js 를 감싸고 있는 html
// page.js : body태그에 작성할 코드
// global.css : layout.js에 포함된 css (모든곳에서 사용)
// page.module.css : page.js 전용 css 
// favicon.ico 삭제 -> public 폴더에 이미지 넣기 -> 


// vercel 에 업로드시
// github에 프로젝트 업로드
// vercel 로그인
// new Project
// 업로드한 프로젝트 Import
// [install Command OVERRIDE] -> npm install 
// .env.local 데이터를 Environment Variales 에 모두 임력
// Deploy 클릭