import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Header from "@/components/header/header";
import navLogo from '@/assets/grouplogo.png';


const inter = Inter({ subsets: ["latin"] });

// metadata : <head></head> 태그에 들어갈 코드 
export const metadata = {
  title: "우리 동아리",
  description: "Generated by create next app",
  icons:{
    icon:'/grouplogo.png'    
  } 
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <Header/>
        {/* children == page.js */}
        {children}
        </body>
    </html>
  );
}

// 기본생성시
// layous.js  : page.js 를 감싸고 있는 html
// page.js : body태그에 작성할 코드
// global.css : layout.js에 포함된 css (모든곳에서 사용)
// page.module.css : page.js 전용 css 
// favicon.ico 삭제 -> public 폴더에 이미지 넣기 -> 
